// <copyright file="MusicTrackBar.cs" company="Emoore">
//   Copyright © EMoore. All rights reserved.
// </copyright>
// <autogenerated />

namespace MusicApplication
{
    using System;
    using System.Windows.Forms;

    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
            DatabaseConnHelper DatabaseObj = new DatabaseConnHelper();
        }
    }
}
