// <copyright file="MusicButton.Designer.cs" company="Emoore">
//   Copyright © EMoore. All rights reserved.
// </copyright>
// <auto-generated />

namespace MusicPlayerButton
{
    public partial class MusicButton
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // MusicButton
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Name = "MusicButton";
            this.Size = new System.Drawing.Size(50, 20);
            this.Load += new System.EventHandler(this.MusicButton_Load);
            this.MouseEnter += new System.EventHandler(this.MusicButton_MouseEnter);
            this.MouseLeave += new System.EventHandler(this.MusicButton_MouseLeave);
            this.ResumeLayout(false);

        }

        #endregion
    }
}
