// <copyright file="MusicButton.Designer.cs" company="Emoore">
//   Copyright © EMoore. All rights reserved.
// </copyright>
// <auto-generated />

namespace MusicPlayArea
{
    partial class MusicArea
    {
        private System.ComponentModel.IContainer components = null;
        
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.currentTimeLabel = new System.Windows.Forms.Label();
            this.maximumTimeLabel = new System.Windows.Forms.Label();
            this.minimumTimeLabel = new System.Windows.Forms.Label();
            this.progressBarCustom1 = new CustomBar.ProgressBarCustom();
            this.PauseButton = new MusicPlayerButton.MusicButton();
            this.StopButton = new MusicPlayerButton.MusicButton();
            this.ShuffleButton = new MusicPlayerButton.MusicButton();
            this.ReplayButton = new MusicPlayerButton.MusicButton();
            this.PlayAllButton = new MusicPlayerButton.MusicButton();
            this.PlayButton = new MusicPlayerButton.MusicButton();
            this.SuspendLayout();
            // 
            // currentTimeLabel
            // 
            this.currentTimeLabel.AutoSize = true;
            this.currentTimeLabel.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.currentTimeLabel.Font = new System.Drawing.Font("Comic Sans MS", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.currentTimeLabel.ForeColor = System.Drawing.Color.Red;
            this.currentTimeLabel.Location = new System.Drawing.Point(193, 3);
            this.currentTimeLabel.MaximumSize = new System.Drawing.Size(50, 50);
            this.currentTimeLabel.MinimumSize = new System.Drawing.Size(40, 20);
            this.currentTimeLabel.Name = "currentTimeLabel";
            this.currentTimeLabel.Size = new System.Drawing.Size(40, 20);
            this.currentTimeLabel.TabIndex = 1;
            this.currentTimeLabel.Text = "0.00";
            this.currentTimeLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // maximumTimeLabel
            // 
            this.maximumTimeLabel.AutoSize = true;
            this.maximumTimeLabel.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.maximumTimeLabel.Font = new System.Drawing.Font("Comic Sans MS", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.maximumTimeLabel.ForeColor = System.Drawing.Color.Red;
            this.maximumTimeLabel.Location = new System.Drawing.Point(382, 3);
            this.maximumTimeLabel.MaximumSize = new System.Drawing.Size(50, 50);
            this.maximumTimeLabel.MinimumSize = new System.Drawing.Size(40, 20);
            this.maximumTimeLabel.Name = "maximumTimeLabel";
            this.maximumTimeLabel.Size = new System.Drawing.Size(40, 20);
            this.maximumTimeLabel.TabIndex = 2;
            this.maximumTimeLabel.Text = "0.00";
            this.maximumTimeLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // minimumTimeLabel
            // 
            this.minimumTimeLabel.AutoSize = true;
            this.minimumTimeLabel.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.minimumTimeLabel.Font = new System.Drawing.Font("Comic Sans MS", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.minimumTimeLabel.ForeColor = System.Drawing.Color.Red;
            this.minimumTimeLabel.Location = new System.Drawing.Point(3, 3);
            this.minimumTimeLabel.MaximumSize = new System.Drawing.Size(50, 50);
            this.minimumTimeLabel.MinimumSize = new System.Drawing.Size(40, 20);
            this.minimumTimeLabel.Name = "minimumTimeLabel";
            this.minimumTimeLabel.Size = new System.Drawing.Size(40, 20);
            this.minimumTimeLabel.TabIndex = 3;
            this.minimumTimeLabel.Text = "0.00";
            this.minimumTimeLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // progressBarCustom1
            // 
            this.progressBarCustom1.BackColor = System.Drawing.SystemColors.Window;
            this.progressBarCustom1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.progressBarCustom1.ForeColor = System.Drawing.SystemColors.Highlight;
            this.progressBarCustom1.Location = new System.Drawing.Point(3, 23);
            this.progressBarCustom1.MaxTime = 150;
            this.progressBarCustom1.Name = "progressBarCustom1";
            this.progressBarCustom1.Size = new System.Drawing.Size(419, 14);
            this.progressBarCustom1.TabIndex = 0;
            this.progressBarCustom1.Value = 150;
            // 
            // PauseButton
            // 
            this.PauseButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PauseButton.Location = new System.Drawing.Point(93, 3);
            this.PauseButton.Margin = new System.Windows.Forms.Padding(0);
            this.PauseButton.Name = "PauseButton";
            this.PauseButton.NotHoverImage = null;
            this.PauseButton.OnHoverImage = null;
            this.PauseButton.Size = new System.Drawing.Size(50, 20);
            this.PauseButton.TabIndex = 5;
            // 
            // StopButton
            // 
            this.StopButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.StopButton.Location = new System.Drawing.Point(143, 3);
            this.StopButton.Name = "StopButton";
            this.StopButton.NotHoverImage = null;
            this.StopButton.OnHoverImage = null;
            this.StopButton.Size = new System.Drawing.Size(50, 20);
            this.StopButton.TabIndex = 6;
            // 
            // ShuffleButton
            // 
            this.ShuffleButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ShuffleButton.Location = new System.Drawing.Point(233, 3);
            this.ShuffleButton.Name = "ShuffleButton";
            this.ShuffleButton.NotHoverImage = null;
            this.ShuffleButton.OnHoverImage = null;
            this.ShuffleButton.Size = new System.Drawing.Size(50, 20);
            this.ShuffleButton.TabIndex = 7;
            // 
            // ReplayButton
            // 
            this.ReplayButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ReplayButton.Location = new System.Drawing.Point(283, 3);
            this.ReplayButton.Name = "ReplayButton";
            this.ReplayButton.NotHoverImage = null;
            this.ReplayButton.OnHoverImage = null;
            this.ReplayButton.Size = new System.Drawing.Size(50, 20);
            this.ReplayButton.TabIndex = 8;
            // 
            // PlayAllButton
            // 
            this.PlayAllButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PlayAllButton.Location = new System.Drawing.Point(333, 3);
            this.PlayAllButton.Name = "PlayAllButton";
            this.PlayAllButton.NotHoverImage = null;
            this.PlayAllButton.OnHoverImage = null;
            this.PlayAllButton.Size = new System.Drawing.Size(50, 20);
            this.PlayAllButton.TabIndex = 9;
            // 
            // PlayButton
            // 
            this.PlayButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PlayButton.Location = new System.Drawing.Point(43, 3);
            this.PlayButton.Margin = new System.Windows.Forms.Padding(0);
            this.PlayButton.Name = "PlayButton";
            this.PlayButton.NotHoverImage = null;
            this.PlayButton.OnHoverImage = null;
            this.PlayButton.Size = new System.Drawing.Size(50, 20);
            this.PlayButton.TabIndex = 4;
            // 
            // MusicArea
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.PlayAllButton);
            this.Controls.Add(this.ReplayButton);
            this.Controls.Add(this.ShuffleButton);
            this.Controls.Add(this.StopButton);
            this.Controls.Add(this.PauseButton);
            this.Controls.Add(this.PlayButton);
            this.Controls.Add(this.minimumTimeLabel);
            this.Controls.Add(this.maximumTimeLabel);
            this.Controls.Add(this.currentTimeLabel);
            this.Controls.Add(this.progressBarCustom1);
            this.DoubleBuffered = true;
            this.Name = "MusicArea";
            this.Size = new System.Drawing.Size(425, 40);
            this.SizeChanged += new System.EventHandler(this.MusicArea_SizeChanged);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private CustomBar.ProgressBarCustom progressBarCustom1;
        private System.Windows.Forms.Label currentTimeLabel;
        private System.Windows.Forms.Label maximumTimeLabel;
        private System.Windows.Forms.Label minimumTimeLabel;
        private MusicPlayerButton.MusicButton PauseButton;
        private MusicPlayerButton.MusicButton StopButton;
        private MusicPlayerButton.MusicButton ShuffleButton;
        private MusicPlayerButton.MusicButton ReplayButton;
        private MusicPlayerButton.MusicButton PlayAllButton;
        private MusicPlayerButton.MusicButton PlayButton;
    }
}
